### ISSUE TITLE
Converting checkbox fields to standard WP storage

### ISSUE THREAD

**Issue by jambojet** [Hube2/custom-field-converter#1]
Can you give an example of code how to convert checkbox fields to standard WP storage.
I need it for pre_get_posts meta_value.

Tank you for plugin!

**Comment by Hube2** [comment]
Are you looking for information on how you take a checkbox field and store it the way WP does or are you looking for how to use the fields that this plugin creates?

**Comment by jambojet** [comment]
I am looking for information on how you take a checkbox field and store it the way WP.

**Comment by Hube2** [comment]
ACF stores data for a checkbox as a serialized array. To get the stored values
```
$values = maybe_unserialize(get_post_meta($post_id, $field_name, true));
if (!is_array($values)) {
  $values = array($values);
}
```
Then you need to put it into a different field, with a different field name. You should also clear out what's already in there before you start just to be on the safe side.
```
delete_post_meta($post_id, $new_field_name);
foreach ($values as $value) {
  add_post_,meta($post_id, $new_field_name, $value, false);
}
```
or more information you should see the WP documents on the functions I used.

**Comment by jambojet** [comment]
Thank you!!!
I think your answer is what I was looking for.
